/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as TreningRouteImport } from './routes/trening'
import { Route as StreetRouteImport } from './routes/street'
import { Route as RegeneracjaRouteImport } from './routes/regeneracja'
import { Route as PrzepisyRouteImport } from './routes/przepisy'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as CwiczeniaRouteImport } from './routes/cwiczenia'
import { Route as BiegiRouteImport } from './routes/biegi'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const TreningRoute = TreningRouteImport.update({
  id: '/trening',
  path: '/trening',
  getParentRoute: () => rootRouteImport,
} as any)
const StreetRoute = StreetRouteImport.update({
  id: '/street',
  path: '/street',
  getParentRoute: () => rootRouteImport,
} as any)
const RegeneracjaRoute = RegeneracjaRouteImport.update({
  id: '/regeneracja',
  path: '/regeneracja',
  getParentRoute: () => rootRouteImport,
} as any)
const PrzepisyRoute = PrzepisyRouteImport.update({
  id: '/przepisy',
  path: '/przepisy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const CwiczeniaRoute = CwiczeniaRouteImport.update({
  id: '/cwiczenia',
  path: '/cwiczenia',
  getParentRoute: () => rootRouteImport,
} as any)
const BiegiRoute = BiegiRouteImport.update({
  id: '/biegi',
  path: '/biegi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biegi': typeof BiegiRoute
  '/cwiczenia': typeof CwiczeniaRoute
  '/dieta': typeof DietaRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/przepisy': typeof PrzepisyRoute
  '/regeneracja': typeof RegeneracjaRoute
  '/street': typeof StreetRoute
  '/trening': typeof TreningRoute
  '/ustawienia': typeof UstawieniaRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biegi': typeof BiegiRoute
  '/cwiczenia': typeof CwiczeniaRoute
  '/dieta': typeof DietaRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/przepisy': typeof PrzepisyRoute
  '/regeneracja': typeof RegeneracjaRoute
  '/street': typeof StreetRoute
  '/trening': typeof TreningRoute
  '/ustawienia': typeof UstawieniaRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biegi': typeof BiegiRoute
  '/cwiczenia': typeof CwiczeniaRoute
  '/dieta': typeof DietaRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profil': typeof ProfilRoute
  '/promo': typeof PromoRoute
  '/przepisy': typeof PrzepisyRoute
  '/regeneracja': typeof RegeneracjaRoute
  '/street': typeof StreetRoute
  '/trening': typeof TreningRoute
  '/ustawienia': typeof UstawieniaRoute
  '/workouts': typeof WorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biegi'
    | '/cwiczenia'
    | '/dieta'
    | '/onboarding'
    | '/premium'
    | '/profil'
    | '/promo'
    | '/przepisy'
    | '/regeneracja'
    | '/street'
    | '/trening'
    | '/ustawienia'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biegi'
    | '/cwiczenia'
    | '/dieta'
    | '/onboarding'
    | '/premium'
    | '/profil'
    | '/promo'
    | '/przepisy'
    | '/regeneracja'
    | '/street'
    | '/trening'
    | '/ustawienia'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/biegi'
    | '/cwiczenia'
    | '/dieta'
    | '/onboarding'
    | '/premium'
    | '/profil'
    | '/promo'
    | '/przepisy'
    | '/regeneracja'
    | '/street'
    | '/trening'
    | '/ustawienia'
    | '/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiegiRoute: typeof BiegiRoute
  CwiczeniaRoute: typeof CwiczeniaRoute
  DietaRoute: typeof DietaRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  ProfilRoute: typeof ProfilRoute
  PromoRoute: typeof PromoRoute
  PrzepisyRoute: typeof PrzepisyRoute
  RegeneracjaRoute: typeof RegeneracjaRoute
  StreetRoute: typeof StreetRoute
  TreningRoute: typeof TreningRoute
  UstawieniaRoute: typeof UstawieniaRoute
  WorkoutsRoute: typeof WorkoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trening': {
      id: '/trening'
      path: '/trening'
      fullPath: '/trening'
      preLoaderRoute: typeof TreningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/street': {
      id: '/street'
      path: '/street'
      fullPath: '/street'
      preLoaderRoute: typeof StreetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regeneracja': {
      id: '/regeneracja'
      path: '/regeneracja'
      fullPath: '/regeneracja'
      preLoaderRoute: typeof RegeneracjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/przepisy': {
      id: '/przepisy'
      path: '/przepisy'
      fullPath: '/przepisy'
      preLoaderRoute: typeof PrzepisyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cwiczenia': {
      id: '/cwiczenia'
      path: '/cwiczenia'
      fullPath: '/cwiczenia'
      preLoaderRoute: typeof CwiczeniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biegi': {
      id: '/biegi'
      path: '/biegi'
      fullPath: '/biegi'
      preLoaderRoute: typeof BiegiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiegiRoute: BiegiRoute,
  CwiczeniaRoute: CwiczeniaRoute,
  DietaRoute: DietaRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  ProfilRoute: ProfilRoute,
  PromoRoute: PromoRoute,
  PrzepisyRoute: PrzepisyRoute,
  RegeneracjaRoute: RegeneracjaRoute,
  StreetRoute: StreetRoute,
  TreningRoute: TreningRoute,
  UstawieniaRoute: UstawieniaRoute,
  WorkoutsRoute: WorkoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
